import type { Organization } from "@/lib/api/contracts";
import treasurySnapshots from "./treasury-snapshots.json";
import treasurySources from "./treasury-sources.json";

export const DEMO_ORGANIZATION: Organization = {
  id: "example-constructora",
  name: "Constructora Encino",
  legalName: "Constructora Encino S.A. de C.V.",
  rfc: "TEN210315AB1",
  currency: "MXN",
  timeZone: "America/Mexico_City",
  minimumCashReserve: "40000.00",
  dailyOperatingExpense: "1200.00",
  role: "owner",
  permissions: [
    "dashboard:read",
    "organization:read",
    "cfdi:read",
    "bank-account:read",
    "bank-transaction:read",
    "connection:read",
    "connection:create",
    "connection:sync",
    "connection:update",
    "connection:revoke",
    "cfdi:import",
    "forecast:read",
    "forecast:run",
    "forecast:configure",
    "organization:update",
    "member:read",
    "member:invite",
    "member:update",
    "member:remove",
    "recommendation:update",
  ],
};

export const DEMO_DATA: Record<string, unknown> = {
  ...treasurySnapshots,
  ...treasurySources,
  "bank/accounts": [
    {
      id: "example-account",
      connectionId: "example-bank",
      name: "Cuenta de operación",
      type: "Checking",
      currency: "MXN",
      balance: "185000.00",
      lastSyncedAt: "2026-09-12T15:42:00Z",
    },
  ],
  "bank/transactions": [
    {
      id: "t-1",
      description: "Cobro de Casa Roble · estimación 02",
      direction: "inflow",
      amount: "24500.00",
      postedAt: "2026-09-12T15:30:00Z",
      category: "Ventas",
    },
    {
      id: "t-2",
      description: "Maderas del Norte · materiales",
      direction: "outflow",
      amount: "12800.00",
      postedAt: "2026-09-11T17:15:00Z",
      category: "Materiales",
    },
    {
      id: "t-3",
      description: "Cobro de Obra Senda · estimación 01",
      direction: "inflow",
      amount: "18000.00",
      postedAt: "2026-09-10T16:00:00Z",
      category: "Ventas",
    },
    {
      id: "t-4",
      description: "Renta de bodega y patio",
      direction: "outflow",
      amount: "15000.00",
      postedAt: "2026-09-09T14:00:00Z",
      category: "Bodega",
    },
    {
      id: "t-5",
      description: "Ferretería Central",
      direction: "outflow",
      amount: "3750.00",
      postedAt: "2026-09-08T16:00:00Z",
      category: "Materiales",
    },
  ].map((item) => ({
    ...item,
    currency: "MXN",
    bankAccountId: "example-account",
    status: "completed",
  })),
  connections: [
    {
      id: "example-bank",
      kind: "bank",
      provider: "nessie",
      displayName: "Cuenta de operación",
      status: "active",
      lastSyncedAt: "2026-09-12T15:42:00Z",
      lastErrorCode: null,
      externalCustomerId: null,
    },
    {
      id: "example-cfdi",
      kind: "cfdi",
      provider: "synthetic_cfdi",
      displayName: "Facturas de ejemplo",
      status: "active",
      lastSyncedAt: null,
      lastErrorCode: null,
      externalCustomerId: null,
    },
  ],
};
